### ISSUE TITLE
Differences between ember-material-lite and  ember-cli-materialize

### ISSUE THREAD

**Issue by vsymguysung** [truenorth/ember-material-lite#28]
I am wondering about the differences between the two addons.
Could you give me the answers? Thanks.

**Comment by truenorth** [comment]
* ember-material-lite wraps around [Material Design Lite](http://getmdl.io), giving you ember components that are ready to use
* ember-cli-materialize wraps around [Materialize.css](http://materializecss.com), doing a lot of the same things.


I will continue to support both addons, but ember-material-lite is newer, faster, and more robust. It is what I'd recommend using for new apps.

**Comment by guysung** [comment]
Thanks much for the detailed answer and great addon!!

**Comment by cimtico** [comment]
will mdl eventually replace cli-materialize? if so, will mdl get some of materialize features such as the date picker?

**Comment by mike-north** [comment]
The two projects are completely separate, due to material design lite and
materialize being completely separate.

**Comment by dalpo** [comment]
:+1:

**Comment by heat** [comment]
Glad to see an effort to maintain both but I suggest focus only one because the result will be a more robust and refined project.
