### ISSUE TITLE
Fails on install

### ISSUE THREAD

**Issue by paddleman** [truenorth/ember-material-lite#6]
For some reason, I am unable to install this as an addon. 
On Ubuntu 14.04; io.js v0.12.6; ember-cli 1.13; npm 1.12.1

I get the following:
```
home/dj/code/projects/1-13/tito/client/node_modules/ember-material-lite/blueprints/ember-material-lite/index.js:6
  beforeInstall: function (options) {
  ^^^^^^^^^^^^^
Unexpected identifier
/home/dj/code/projects/1-13/tito/client/node_modules/ember-material-lite/blueprints/ember-material-lite/index.js:6
  beforeInstall: function (options) {
  ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (/home/dj/code/projects/1-13/tito/client/node_modules/ember-cli/lib/models/blueprint.js:1239:25)
    at Function.Blueprint.lookup (/home/dj/code/projects/1-13/tito/client/node_modules/ember-cli/lib/models/blueprint.js:1214:24)
    at Class.module.exports.Task.extend.lookupBlueprint (/home/dj/code/projects/1-13/tito/client/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:91:22)
```
Thanks for the efforts.
DJ

**Comment by wcurtis** [comment]
Same issue on OSX with ember-cli 1.13.1. 

For a temp work-around I manually added the bower/npm packages these functions would have installed.

**Comment by truenorth** [comment]
Releasing a new version in a few minutes with a fix for this. Thanks for the bug report gents

**Comment by truenorth** [comment]
Alright, `v0.0.5` should work better. There are still some manual steps (the blueprint will tell you what to do) until https://github.com/ember-cli/ember-cli/issues/4425 is resolved.

**Comment by wcurtis** [comment]
:+1: thanks!

**Comment by paddleman** [comment]
I tried the new version of ember-material-lite and ran into a few problems still.  I also am using the master branch of ember-cli ```version: 1.13.1-master-cc06d7b18b```` to see if recent PRs fixed the issue: it did,  but a new complaint arose:
```
Installed packages for tooling via npm.
installing ember-material-lite
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```
The following workaround seems to work an let you work with material design lite in ember:
I installed ember-cli-sass prior to running ```ember install ember-material-lite```

I added the following to my ```bower.json``` file (the -src file because I want to use sass):

``` javascript
 "material-design-lite": "1.0.0",
 "material-design-lite-src": "https://github.com/google/material-design-lite.git#37286ae139b0ae336a8a7e9ed3b18ace1abff7ed"
```
Run:
``` bower install ```

It then complained about at scss file:

```
File: bower_components/material-design-lite-src/src/_variables.scss (308)
Incompatible units: 'ms' and 'deg'
```
After a google search, removing the 'ms' units on line 308 of the offending file seemed to quash the error.

Thanks again for your efforts; I look forward to using the package.
DJ
