### ISSUE TITLE
Loading Spinners Not Working

### ISSUE THREAD

**Issue by nahtnam** [truenorth/ember-material-lite#7]
Hey!

The loading spinners arent working if you switch to it from a different view.

Reproduce:
1. Go to http://mike.works/ember-material-lite/#/buttons
2. Press progress in the navbar.
3. You will see this: http://i.imgur.com/zBvrnYQ.png
4. Reload the page, and you will see the normal spinners. http://i.imgur.com/cLAdfzX.png
5. I think it has something to with the js not reloading after the view has been switched.

Thanks.

**Comment by nahtnam** [comment]
Same applies with the ripples on buttons.

**Comment by truenorth** [comment]
yep, this has to do with the way the JavaScript component of material lite works. we'll have to either write our own equivalent or hijack it so we have more control over when it updates the DOM

**Comment by nahtnam** [comment]
I was trying to mess around with this before, and was wondering if it would be possible to re-run the js every time the view changes?

**Comment by Patrick-Wanger** [comment]
hey what up manthan! it's patrick

**Comment by truenorth** [comment]
@nahtnam I'm dissecting the material-lite javascript, and it looks like all of the various modules register themselves when they're eval'd. I can hijack this mechanism to register them to something else, and allow the code to be run via a shared service of some sort. 

May be a few days before I can get around to adding this

**Comment by nahtnam** [comment]
@truenorth Sounds good. Thanks.

**Comment by henriquecf** [comment]
Nice

**Comment by truenorth** [comment]
@nahtnam This should be working now.
